### ISSUE TITLE
YouTube shorts downloaded without sound

### ISSUE THREAD

**Issue by finnlogin** [ssebastianoo/yt-dlp-telegram#10]
Hi there!

I've noticed a problem with downloading shorts from YouTube. For some reason, they are being downloaded without sound. However, when I download them using yt-dlp in Terminal, everything works just fine.

Thank you for the bot. I hope you can fix the issue soon.

update:
The same issue occurs with normal YouTube videos and Reddit videos.

**Comment by ssebastianoo** [comment]
Sorry for the late response, I had to update yt-dlp, should be fixed now

**Comment by finnlogin** [comment]
> Sorry for the late response, I had to update yt-dlp, should be fixed now

YouTube Shorts work just fine, but Reddit videos are still being downloaded without sound.
