### ISSUE TITLE
How I Set The Quality Video?

### ISSUE THREAD

**Issue by JohanChungus** [ssebastianoo/yt-dlp-telegram#2]

**Comment by ssebastianoo** [comment]
> 

editing `format` in the yt-dlp options [here](https://github.com/ssebastianoo/yt-dlp-telegram/blob/master/main.py#L63), I'll probably add a flag to select it from the bot

**Comment by JohanChungus** [comment]
How I Edit and Set 4K Video
Also When I send the video more than 50mb is not working its say **A request to the Telegram API was unsuccessful. Error code: 413. Description: Request Entity Too Large**

**Comment by ssebastianoo** [comment]
telegram can't handle big files from bots, there's nothing you can do about it.

to set the quality check the [yt-dlp docs](https://github.com/yt-dlp/yt-dlp#format-selection)

**Comment by JohanChungus** [comment]
Hmm Ok:( I Will Close The Comment
