### ISSUE TITLE
Choose video resolution in telegram

### ISSUE THREAD

**Issue by Damontools32** [ssebastianoo/yt-dlp-telegram#3]
I would like to have an option to choose lower quality to download video. I run your script on my Ubuntu server and made a config.py file and connected it to my channel . As you know we can't upload videos bigger than 100 mg so I want something with lower quality . How is it possible to change setting to download with lower quality?

**Comment by Damontools32** [comment]
Yes I tried it but didn't work it says in bot videos should not exceed 100 mb even when I changed max size to 20000000

**Comment by ssebastianoo** [comment]
You can now use the `/custom video_url` command

**Comment by Damontools32** [comment]
Thank you. It's working like a charm. 
How can we increase upload size ?
