### ISSUE TITLE
Getting a error when uploading

### ISSUE THREAD

**Issue by SanujaNS** [ssebastianoo/yt-dlp-telegram#4]
Hello @ssebastianoo
I'm getting "Couldn't send file, make sure it's supported by Telegram and it doesn't exceed 2097MB" error even video is only 67MB.
Uploads are working fine under 50MB.

Please look into this issue. I'm looking forward for a solution.

Thank you.

**Comment by ssebastianoo** [comment]
Hi, sorry but there's nothing I can do about it, it's a telegram limitation

https://github.com/ssebastianoo/yt-dlp-telegram/issues/3#issuecomment-1587720164
