### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by cataldoc** [ssebastianoo/yt-dlp-telegram#8]
Hi

I'm having issues with some links from TikTok. The problem is happening when the video file name is very long.
I have the same issue when I use yt-dlp from the command line but I can solve it by using the -o switch with an arbitrary short name.

The bot is running on Linux (ext4 filesystem)

Example with this link: https://vm.tiktok.com/ZGJTg4LLV

This is the resulting error
ERROR: unable to open for writing: [Errno 36] File name too long: 'outputs/SYNTHONY performs @faithlessofficial “Insomnia” with vocals from @jujulipps. 🔥 “Insomnia” was released on the 27th November 1995 and has had 134 million views on YouTube. 🤯 In honour of the one and only Maxi Jazz, Watch the live SYNTHONY version here： ⬇️ https：⧸⧸youtube.com⧸@SYNTHONYLIVE #SYNTHONY #AFestivalLikeNoOther #Orchestra #Insomnia #Faithless #LiveMusic #DanceMusic.mp4.part'

Would it be possible to use a random (short) filename for the output file so that the temp file will get written no matter what the original filename was?

**Comment by feboss** [comment]
Line 64 of main.py i modified with   

`     with yt_dlp.YoutubeDL({'format': format_id, 'outtmpl': 'outputs/a.%(ext)s', 'progress_hooks': [progress], 'postprocessors': [{  # Extract audio using ffmpeg
`

i don't care about filename.

Btw the best thing to do is if i have error on filename, use outtmpl': 'outputs/rRANDON3LETTER.%(ext)s'

**Comment by ssebastianoo** [comment]
fixed in aba40b214db6d9b396701f7190e8dca524cd3407
